########################################################################
# Jekyll Blog Settings. 
########################################################################
#
# Site Basic Info; 
#
# Markdown type, such as: rdiscount, maruku
markdown: rdiscount
# URL style. 
permalink: /:year/:month/:title/
# 
pygments: true
# 
paginate: 16
# Your name. 
author: Justin GAO
# Your blog's URL address.
url: http://justingao.github.io
# 
# Personal Info; 
# 
my: 
    # Your email.
    email: justin@leigao.org
    # GitHub Account. 
    github: justingao
#
# Disqus settings. 
#
disqus:
    # Disqus short name; 
    shortname: justingao
# 
# Google Analytics; 
#
ga: 
    # Google Analytics ID; 
    id: UA-52005096-1
    # Google Analytics Site URL; 
    uri: justingao.github.io
